// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol/vessel.proto

package vessel

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Vessel struct {
	VesselId             string   `protobuf:"bytes,1,opt,name=vesselId,proto3" json:"vesselId,omitempty"`
	Capacity             int32    `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	MaxWeight            int32    `protobuf:"varint,3,opt,name=maxWeight,proto3" json:"maxWeight,omitempty"`
	VesselName           string   `protobuf:"bytes,4,opt,name=vesselName,proto3" json:"vesselName,omitempty"`
	Available            bool     `protobuf:"varint,5,opt,name=available,proto3" json:"available,omitempty"`
	OwnerId              string   `protobuf:"bytes,6,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vessel) Reset()         { *m = Vessel{} }
func (m *Vessel) String() string { return proto.CompactTextString(m) }
func (*Vessel) ProtoMessage()    {}
func (*Vessel) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c0d8e0d06c6934b, []int{0}
}

func (m *Vessel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vessel.Unmarshal(m, b)
}
func (m *Vessel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vessel.Marshal(b, m, deterministic)
}
func (m *Vessel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vessel.Merge(m, src)
}
func (m *Vessel) XXX_Size() int {
	return xxx_messageInfo_Vessel.Size(m)
}
func (m *Vessel) XXX_DiscardUnknown() {
	xxx_messageInfo_Vessel.DiscardUnknown(m)
}

var xxx_messageInfo_Vessel proto.InternalMessageInfo

func (m *Vessel) GetVesselId() string {
	if m != nil {
		return m.VesselId
	}
	return ""
}

func (m *Vessel) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *Vessel) GetMaxWeight() int32 {
	if m != nil {
		return m.MaxWeight
	}
	return 0
}

func (m *Vessel) GetVesselName() string {
	if m != nil {
		return m.VesselName
	}
	return ""
}

func (m *Vessel) GetAvailable() bool {
	if m != nil {
		return m.Available
	}
	return false
}

func (m *Vessel) GetOwnerId() string {
	if m != nil {
		return m.OwnerId
	}
	return ""
}

type FindAvailableReq struct {
	Capacity             int32    `protobuf:"varint,1,opt,name=capacity,proto3" json:"capacity,omitempty"`
	MaxWeight            int32    `protobuf:"varint,2,opt,name=maxWeight,proto3" json:"maxWeight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindAvailableReq) Reset()         { *m = FindAvailableReq{} }
func (m *FindAvailableReq) String() string { return proto.CompactTextString(m) }
func (*FindAvailableReq) ProtoMessage()    {}
func (*FindAvailableReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c0d8e0d06c6934b, []int{1}
}

func (m *FindAvailableReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAvailableReq.Unmarshal(m, b)
}
func (m *FindAvailableReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAvailableReq.Marshal(b, m, deterministic)
}
func (m *FindAvailableReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAvailableReq.Merge(m, src)
}
func (m *FindAvailableReq) XXX_Size() int {
	return xxx_messageInfo_FindAvailableReq.Size(m)
}
func (m *FindAvailableReq) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAvailableReq.DiscardUnknown(m)
}

var xxx_messageInfo_FindAvailableReq proto.InternalMessageInfo

func (m *FindAvailableReq) GetCapacity() int32 {
	if m != nil {
		return m.Capacity
	}
	return 0
}

func (m *FindAvailableReq) GetMaxWeight() int32 {
	if m != nil {
		return m.MaxWeight
	}
	return 0
}

type FindAvailableRsp struct {
	Vessel               *Vessel   `protobuf:"bytes,1,opt,name=vessel,proto3" json:"vessel,omitempty"`
	Vessels              []*Vessel `protobuf:"bytes,2,rep,name=vessels,proto3" json:"vessels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *FindAvailableRsp) Reset()         { *m = FindAvailableRsp{} }
func (m *FindAvailableRsp) String() string { return proto.CompactTextString(m) }
func (*FindAvailableRsp) ProtoMessage()    {}
func (*FindAvailableRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c0d8e0d06c6934b, []int{2}
}

func (m *FindAvailableRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAvailableRsp.Unmarshal(m, b)
}
func (m *FindAvailableRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAvailableRsp.Marshal(b, m, deterministic)
}
func (m *FindAvailableRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAvailableRsp.Merge(m, src)
}
func (m *FindAvailableRsp) XXX_Size() int {
	return xxx_messageInfo_FindAvailableRsp.Size(m)
}
func (m *FindAvailableRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAvailableRsp.DiscardUnknown(m)
}

var xxx_messageInfo_FindAvailableRsp proto.InternalMessageInfo

func (m *FindAvailableRsp) GetVessel() *Vessel {
	if m != nil {
		return m.Vessel
	}
	return nil
}

func (m *FindAvailableRsp) GetVessels() []*Vessel {
	if m != nil {
		return m.Vessels
	}
	return nil
}

type CreateReq struct {
	VesselInfo           *Vessel  `protobuf:"bytes,1,opt,name=vesselInfo,proto3" json:"vesselInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReq) Reset()         { *m = CreateReq{} }
func (m *CreateReq) String() string { return proto.CompactTextString(m) }
func (*CreateReq) ProtoMessage()    {}
func (*CreateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c0d8e0d06c6934b, []int{3}
}

func (m *CreateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReq.Unmarshal(m, b)
}
func (m *CreateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReq.Marshal(b, m, deterministic)
}
func (m *CreateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReq.Merge(m, src)
}
func (m *CreateReq) XXX_Size() int {
	return xxx_messageInfo_CreateReq.Size(m)
}
func (m *CreateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReq proto.InternalMessageInfo

func (m *CreateReq) GetVesselInfo() *Vessel {
	if m != nil {
		return m.VesselInfo
	}
	return nil
}

type CreateRsp struct {
	VesCreated           bool      `protobuf:"varint,1,opt,name=vesCreated,proto3" json:"vesCreated,omitempty"`
	VesselInfos          []*Vessel `protobuf:"bytes,2,rep,name=vesselInfos,proto3" json:"vesselInfos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateRsp) Reset()         { *m = CreateRsp{} }
func (m *CreateRsp) String() string { return proto.CompactTextString(m) }
func (*CreateRsp) ProtoMessage()    {}
func (*CreateRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c0d8e0d06c6934b, []int{4}
}

func (m *CreateRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRsp.Unmarshal(m, b)
}
func (m *CreateRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRsp.Marshal(b, m, deterministic)
}
func (m *CreateRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRsp.Merge(m, src)
}
func (m *CreateRsp) XXX_Size() int {
	return xxx_messageInfo_CreateRsp.Size(m)
}
func (m *CreateRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRsp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRsp proto.InternalMessageInfo

func (m *CreateRsp) GetVesCreated() bool {
	if m != nil {
		return m.VesCreated
	}
	return false
}

func (m *CreateRsp) GetVesselInfos() []*Vessel {
	if m != nil {
		return m.VesselInfos
	}
	return nil
}

func init() {
	proto.RegisterType((*Vessel)(nil), "go.grpc.server.vessel.Vessel")
	proto.RegisterType((*FindAvailableReq)(nil), "go.grpc.server.vessel.FindAvailableReq")
	proto.RegisterType((*FindAvailableRsp)(nil), "go.grpc.server.vessel.FindAvailableRsp")
	proto.RegisterType((*CreateReq)(nil), "go.grpc.server.vessel.CreateReq")
	proto.RegisterType((*CreateRsp)(nil), "go.grpc.server.vessel.CreateRsp")
}

func init() { proto.RegisterFile("protocol/vessel.proto", fileDescriptor_2c0d8e0d06c6934b) }

var fileDescriptor_2c0d8e0d06c6934b = []byte{
	// 354 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x51, 0x4b, 0xf3, 0x30,
	0x14, 0x25, 0xdb, 0xb7, 0x6e, 0xbb, 0x63, 0x7c, 0x1a, 0x18, 0x84, 0xa1, 0x52, 0xfa, 0xe2, 0x9e,
	0x22, 0x4c, 0xc4, 0x07, 0x11, 0x51, 0x41, 0x98, 0x0c, 0x1f, 0x2a, 0x28, 0xf8, 0x96, 0x75, 0xd7,
	0x59, 0xe8, 0xd6, 0x98, 0x94, 0xaa, 0xaf, 0xfe, 0x28, 0x9f, 0xfd, 0x69, 0xb2, 0x64, 0xed, 0xba,
	0xe1, 0x5c, 0x9f, 0x92, 0x7b, 0xee, 0x3d, 0x87, 0x93, 0x73, 0x09, 0x74, 0xa4, 0x8a, 0x93, 0x38,
	0x88, 0xa3, 0xa3, 0x14, 0xb5, 0xc6, 0x88, 0x9b, 0x9a, 0x76, 0x26, 0x31, 0x9f, 0x28, 0x19, 0x70,
	0x8d, 0x2a, 0x45, 0xc5, 0x6d, 0xd3, 0xfb, 0x22, 0xe0, 0x3c, 0x98, 0x2b, 0xed, 0x42, 0xc3, 0x82,
	0x83, 0x31, 0x23, 0x2e, 0xe9, 0x35, 0xfd, 0xbc, 0x9e, 0xf7, 0x02, 0x21, 0x45, 0x10, 0x26, 0x1f,
	0xac, 0xe2, 0x92, 0x5e, 0xcd, 0xcf, 0x6b, 0xba, 0x07, 0xcd, 0xa9, 0x78, 0x7f, 0xc4, 0x70, 0xf2,
	0x92, 0xb0, 0xaa, 0x69, 0x2e, 0x01, 0x7a, 0x00, 0x60, 0x55, 0xee, 0xc4, 0x14, 0xd9, 0x3f, 0xa3,
	0x5b, 0x40, 0xe6, 0x6c, 0x91, 0x8a, 0x30, 0x12, 0xa3, 0x08, 0x59, 0xcd, 0x25, 0xbd, 0x86, 0xbf,
	0x04, 0x28, 0x83, 0x7a, 0xfc, 0x36, 0x43, 0x35, 0x18, 0x33, 0xc7, 0x50, 0xb3, 0xd2, 0x1b, 0xc2,
	0xce, 0x4d, 0x38, 0x1b, 0x5f, 0x66, 0xa3, 0x3e, 0xbe, 0xae, 0xb8, 0x24, 0x7f, 0xb9, 0xac, 0xac,
	0xb9, 0xf4, 0x3e, 0xc9, 0xba, 0x9c, 0x96, 0xf4, 0x04, 0x1c, 0x6b, 0xd4, 0x88, 0xb5, 0xfa, 0xfb,
	0xfc, 0xd7, 0x0c, 0xb9, 0xcd, 0xcf, 0x5f, 0x0c, 0xd3, 0x53, 0xa8, 0xdb, 0x9b, 0x66, 0x15, 0xb7,
	0xba, 0x9d, 0x97, 0x4d, 0x7b, 0xb7, 0xd0, 0xbc, 0x56, 0x28, 0x12, 0xf3, 0x96, 0xf3, 0x2c, 0xb7,
	0xc1, 0xec, 0x39, 0x2e, 0x67, 0xa0, 0x40, 0xf0, 0xa2, 0x5c, 0x4b, 0xcb, 0xc5, 0x0e, 0x6c, 0x6d,
	0x77, 0xdb, 0xf0, 0x0b, 0x08, 0xbd, 0x80, 0xd6, 0x92, 0x5a, 0xd2, 0x75, 0x91, 0xd1, 0xff, 0x26,
	0xd0, 0xb6, 0xf8, 0x3d, 0xaa, 0x34, 0x0c, 0x90, 0x0a, 0x68, 0xaf, 0xe4, 0x49, 0x0f, 0x37, 0xc8,
	0xad, 0x2f, 0xb1, 0x5b, 0x6e, 0x50, 0x4b, 0x3a, 0x04, 0xc7, 0x3e, 0x80, 0xba, 0x1b, 0x28, 0x79,
	0x9a, 0xdd, 0x2d, 0x13, 0x5a, 0x5e, 0xed, 0x3e, 0xfd, 0xe7, 0x8b, 0x1f, 0x73, 0x66, 0x8f, 0x91,
	0x63, 0x7e, 0xce, 0xf1, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x06, 0x09, 0x1a, 0xfe, 0x52, 0x03,
	0x00, 0x00,
}
