// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: protocol/vessel.proto

package vessel

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/asim/go-micro/v3/api"
	client "github.com/asim/go-micro/v3/client"
	server "github.com/asim/go-micro/v3/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for VesselService service

func NewVesselServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for VesselService service

type VesselService interface {
	FindAvailable(ctx context.Context, in *FindAvailableReq, opts ...client.CallOption) (*FindAvailableRsp, error)
	Create(ctx context.Context, in *CreateReq, opts ...client.CallOption) (*CreateRsp, error)
}

type vesselService struct {
	c    client.Client
	name string
}

func NewVesselService(name string, c client.Client) VesselService {
	return &vesselService{
		c:    c,
		name: name,
	}
}

func (c *vesselService) FindAvailable(ctx context.Context, in *FindAvailableReq, opts ...client.CallOption) (*FindAvailableRsp, error) {
	req := c.c.NewRequest(c.name, "VesselService.FindAvailable", in)
	out := new(FindAvailableRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vesselService) Create(ctx context.Context, in *CreateReq, opts ...client.CallOption) (*CreateRsp, error) {
	req := c.c.NewRequest(c.name, "VesselService.Create", in)
	out := new(CreateRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for VesselService service

type VesselServiceHandler interface {
	FindAvailable(context.Context, *FindAvailableReq, *FindAvailableRsp) error
	Create(context.Context, *CreateReq, *CreateRsp) error
}

func RegisterVesselServiceHandler(s server.Server, hdlr VesselServiceHandler, opts ...server.HandlerOption) error {
	type vesselService interface {
		FindAvailable(ctx context.Context, in *FindAvailableReq, out *FindAvailableRsp) error
		Create(ctx context.Context, in *CreateReq, out *CreateRsp) error
	}
	type VesselService struct {
		vesselService
	}
	h := &vesselServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&VesselService{h}, opts...))
}

type vesselServiceHandler struct {
	VesselServiceHandler
}

func (h *vesselServiceHandler) FindAvailable(ctx context.Context, in *FindAvailableReq, out *FindAvailableRsp) error {
	return h.VesselServiceHandler.FindAvailable(ctx, in, out)
}

func (h *vesselServiceHandler) Create(ctx context.Context, in *CreateReq, out *CreateRsp) error {
	return h.VesselServiceHandler.Create(ctx, in, out)
}
