// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol/consignment.proto

package consignment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Container struct {
	ContainerId          string   `protobuf:"bytes,1,opt,name=containerId,proto3" json:"containerId,omitempty"`
	CustomerId           string   `protobuf:"bytes,2,opt,name=customerId,proto3" json:"customerId,omitempty"`
	Departure            string   `protobuf:"bytes,3,opt,name=departure,proto3" json:"departure,omitempty"`
	UserId               string   `protobuf:"bytes,4,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1afbce55d4bcd41, []int{0}
}

func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (m *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(m, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func (m *Container) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *Container) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *Container) GetDeparture() string {
	if m != nil {
		return m.Departure
	}
	return ""
}

func (m *Container) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type Consignment struct {
	ConsignmentId        string       `protobuf:"bytes,1,opt,name=consignmentId,proto3" json:"consignmentId,omitempty"`
	ConsignmentDesc      string       `protobuf:"bytes,2,opt,name=consignmentDesc,proto3" json:"consignmentDesc,omitempty"`
	ConsignmentWeight    int32        `protobuf:"varint,3,opt,name=consignmentWeight,proto3" json:"consignmentWeight,omitempty"`
	Containers           []*Container `protobuf:"bytes,4,rep,name=containers,proto3" json:"containers,omitempty"`
	VesselId             string       `protobuf:"bytes,5,opt,name=vesselId,proto3" json:"vesselId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Consignment) Reset()         { *m = Consignment{} }
func (m *Consignment) String() string { return proto.CompactTextString(m) }
func (*Consignment) ProtoMessage()    {}
func (*Consignment) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1afbce55d4bcd41, []int{1}
}

func (m *Consignment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Consignment.Unmarshal(m, b)
}
func (m *Consignment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Consignment.Marshal(b, m, deterministic)
}
func (m *Consignment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Consignment.Merge(m, src)
}
func (m *Consignment) XXX_Size() int {
	return xxx_messageInfo_Consignment.Size(m)
}
func (m *Consignment) XXX_DiscardUnknown() {
	xxx_messageInfo_Consignment.DiscardUnknown(m)
}

var xxx_messageInfo_Consignment proto.InternalMessageInfo

func (m *Consignment) GetConsignmentId() string {
	if m != nil {
		return m.ConsignmentId
	}
	return ""
}

func (m *Consignment) GetConsignmentDesc() string {
	if m != nil {
		return m.ConsignmentDesc
	}
	return ""
}

func (m *Consignment) GetConsignmentWeight() int32 {
	if m != nil {
		return m.ConsignmentWeight
	}
	return 0
}

func (m *Consignment) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

func (m *Consignment) GetVesselId() string {
	if m != nil {
		return m.VesselId
	}
	return ""
}

type CreateConsignmentReq struct {
	Consignment          *Consignment `protobuf:"bytes,1,opt,name=consignment,proto3" json:"consignment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateConsignmentReq) Reset()         { *m = CreateConsignmentReq{} }
func (m *CreateConsignmentReq) String() string { return proto.CompactTextString(m) }
func (*CreateConsignmentReq) ProtoMessage()    {}
func (*CreateConsignmentReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1afbce55d4bcd41, []int{2}
}

func (m *CreateConsignmentReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateConsignmentReq.Unmarshal(m, b)
}
func (m *CreateConsignmentReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateConsignmentReq.Marshal(b, m, deterministic)
}
func (m *CreateConsignmentReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateConsignmentReq.Merge(m, src)
}
func (m *CreateConsignmentReq) XXX_Size() int {
	return xxx_messageInfo_CreateConsignmentReq.Size(m)
}
func (m *CreateConsignmentReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateConsignmentReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateConsignmentReq proto.InternalMessageInfo

func (m *CreateConsignmentReq) GetConsignment() *Consignment {
	if m != nil {
		return m.Consignment
	}
	return nil
}

type CreateConsignmentRsp struct {
	Created              bool         `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Consignment          *Consignment `protobuf:"bytes,2,opt,name=Consignment,proto3" json:"Consignment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateConsignmentRsp) Reset()         { *m = CreateConsignmentRsp{} }
func (m *CreateConsignmentRsp) String() string { return proto.CompactTextString(m) }
func (*CreateConsignmentRsp) ProtoMessage()    {}
func (*CreateConsignmentRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1afbce55d4bcd41, []int{3}
}

func (m *CreateConsignmentRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateConsignmentRsp.Unmarshal(m, b)
}
func (m *CreateConsignmentRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateConsignmentRsp.Marshal(b, m, deterministic)
}
func (m *CreateConsignmentRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateConsignmentRsp.Merge(m, src)
}
func (m *CreateConsignmentRsp) XXX_Size() int {
	return xxx_messageInfo_CreateConsignmentRsp.Size(m)
}
func (m *CreateConsignmentRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateConsignmentRsp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateConsignmentRsp proto.InternalMessageInfo

func (m *CreateConsignmentRsp) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *CreateConsignmentRsp) GetConsignment() *Consignment {
	if m != nil {
		return m.Consignment
	}
	return nil
}

type GetConsignmentReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConsignmentReq) Reset()         { *m = GetConsignmentReq{} }
func (m *GetConsignmentReq) String() string { return proto.CompactTextString(m) }
func (*GetConsignmentReq) ProtoMessage()    {}
func (*GetConsignmentReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1afbce55d4bcd41, []int{4}
}

func (m *GetConsignmentReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConsignmentReq.Unmarshal(m, b)
}
func (m *GetConsignmentReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConsignmentReq.Marshal(b, m, deterministic)
}
func (m *GetConsignmentReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConsignmentReq.Merge(m, src)
}
func (m *GetConsignmentReq) XXX_Size() int {
	return xxx_messageInfo_GetConsignmentReq.Size(m)
}
func (m *GetConsignmentReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConsignmentReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetConsignmentReq proto.InternalMessageInfo

type GetConsignmentRsp struct {
	ConsCreated          bool           `protobuf:"varint,1,opt,name=consCreated,proto3" json:"consCreated,omitempty"`
	Consignment          *Consignment   `protobuf:"bytes,2,opt,name=consignment,proto3" json:"consignment,omitempty"`
	Consignments         []*Consignment `protobuf:"bytes,3,rep,name=consignments,proto3" json:"consignments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetConsignmentRsp) Reset()         { *m = GetConsignmentRsp{} }
func (m *GetConsignmentRsp) String() string { return proto.CompactTextString(m) }
func (*GetConsignmentRsp) ProtoMessage()    {}
func (*GetConsignmentRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1afbce55d4bcd41, []int{5}
}

func (m *GetConsignmentRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConsignmentRsp.Unmarshal(m, b)
}
func (m *GetConsignmentRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConsignmentRsp.Marshal(b, m, deterministic)
}
func (m *GetConsignmentRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConsignmentRsp.Merge(m, src)
}
func (m *GetConsignmentRsp) XXX_Size() int {
	return xxx_messageInfo_GetConsignmentRsp.Size(m)
}
func (m *GetConsignmentRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConsignmentRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetConsignmentRsp proto.InternalMessageInfo

func (m *GetConsignmentRsp) GetConsCreated() bool {
	if m != nil {
		return m.ConsCreated
	}
	return false
}

func (m *GetConsignmentRsp) GetConsignment() *Consignment {
	if m != nil {
		return m.Consignment
	}
	return nil
}

func (m *GetConsignmentRsp) GetConsignments() []*Consignment {
	if m != nil {
		return m.Consignments
	}
	return nil
}

func init() {
	proto.RegisterType((*Container)(nil), "go.grpc.server.consignment.Container")
	proto.RegisterType((*Consignment)(nil), "go.grpc.server.consignment.Consignment")
	proto.RegisterType((*CreateConsignmentReq)(nil), "go.grpc.server.consignment.CreateConsignmentReq")
	proto.RegisterType((*CreateConsignmentRsp)(nil), "go.grpc.server.consignment.CreateConsignmentRsp")
	proto.RegisterType((*GetConsignmentReq)(nil), "go.grpc.server.consignment.GetConsignmentReq")
	proto.RegisterType((*GetConsignmentRsp)(nil), "go.grpc.server.consignment.GetConsignmentRsp")
}

func init() { proto.RegisterFile("protocol/consignment.proto", fileDescriptor_a1afbce55d4bcd41) }

var fileDescriptor_a1afbce55d4bcd41 = []byte{
	// 411 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xcd, 0x6e, 0xda, 0x40,
	0x10, 0xc7, 0x65, 0xbe, 0x0a, 0xe3, 0x56, 0x88, 0x69, 0x55, 0xb9, 0x6e, 0x55, 0x21, 0xab, 0x55,
	0x39, 0xb4, 0x6e, 0x45, 0x8f, 0xbd, 0xd5, 0xad, 0x22, 0x94, 0x9b, 0x39, 0x44, 0xca, 0xcd, 0x59,
	0x46, 0xc6, 0x12, 0x78, 0x37, 0xbb, 0x0b, 0x39, 0xe4, 0x98, 0xe7, 0xcb, 0xab, 0xe4, 0x05, 0x72,
	0x89, 0xb2, 0x01, 0xb3, 0xc6, 0x84, 0x84, 0xdc, 0x3c, 0xbf, 0x9d, 0x8f, 0xff, 0xfc, 0xd7, 0x5a,
	0xf0, 0x85, 0xe4, 0x9a, 0x33, 0x3e, 0xfb, 0xc9, 0x78, 0xae, 0xb2, 0x34, 0x9f, 0x53, 0xae, 0x43,
	0x03, 0xd1, 0x4f, 0x79, 0x98, 0x4a, 0xc1, 0x42, 0x45, 0x72, 0x49, 0x32, 0xb4, 0x32, 0x82, 0x2b,
	0x07, 0x3a, 0x11, 0xcf, 0x75, 0x92, 0xe5, 0x24, 0xb1, 0x0f, 0x2e, 0x5b, 0x07, 0xa3, 0x89, 0xe7,
	0xf4, 0x9d, 0x41, 0x27, 0xb6, 0x11, 0x7e, 0x06, 0x60, 0x0b, 0xa5, 0xf9, 0xdc, 0x24, 0xd4, 0x4c,
	0x82, 0x45, 0xf0, 0x13, 0x74, 0x26, 0x24, 0x12, 0xa9, 0x17, 0x92, 0xbc, 0xba, 0x39, 0xde, 0x00,
	0x7c, 0x0f, 0xad, 0x85, 0x32, 0x95, 0x0d, 0x73, 0xb4, 0x8a, 0x82, 0x1b, 0x07, 0xdc, 0x68, 0xa3,
	0x0a, 0xbf, 0xc0, 0x1b, 0x4b, 0x64, 0xa1, 0xa4, 0x0c, 0x71, 0x00, 0x5d, 0x0b, 0xfc, 0x23, 0xc5,
	0x56, 0x82, 0xb6, 0x31, 0x7e, 0x87, 0x9e, 0x85, 0x4e, 0x28, 0x4b, 0xa7, 0xda, 0xa8, 0x6b, 0xc6,
	0xd5, 0x03, 0xfc, 0x0f, 0x50, 0xac, 0xac, 0xbc, 0x46, 0xbf, 0x3e, 0x70, 0x87, 0x5f, 0xc3, 0xc7,
	0x4d, 0x0c, 0x0b, 0x03, 0x63, 0xab, 0x10, 0x7d, 0x68, 0x2f, 0x49, 0x29, 0x9a, 0x8d, 0x26, 0x5e,
	0xd3, 0xe8, 0x2a, 0xe2, 0x20, 0x81, 0x77, 0x91, 0xa4, 0x44, 0x93, 0xb5, 0x75, 0x4c, 0xe7, 0x38,
	0x32, 0x17, 0xb0, 0x26, 0x66, 0x6d, 0x77, 0xf8, 0xed, 0x89, 0xd9, 0x45, 0x03, 0xbb, 0x36, 0xb8,
	0xdc, 0x35, 0x42, 0x09, 0xf4, 0xe0, 0x15, 0x33, 0xfc, 0xc1, 0xd5, 0x76, 0xbc, 0x0e, 0xef, 0x87,
	0x5b, 0xb9, 0xc6, 0xcb, 0x43, 0x86, 0x5b, 0x41, 0xf0, 0x16, 0x7a, 0x47, 0xa4, 0xcb, 0xcb, 0x05,
	0xd7, 0x4e, 0x85, 0x2a, 0xb1, 0xfa, 0xe7, 0x54, 0x54, 0xd2, 0x64, 0xa3, 0x6d, 0x53, 0x6a, 0x2f,
	0x37, 0x05, 0x8f, 0xe1, 0xb5, 0x15, 0x2a, 0xaf, 0x6e, 0x2e, 0xf7, 0xd9, 0xbd, 0x4a, 0xc5, 0xc3,
	0x5b, 0x07, 0xba, 0xe3, 0x69, 0x26, 0x44, 0x96, 0xa7, 0x63, 0x92, 0xcb, 0x8c, 0x11, 0x5e, 0x40,
	0xaf, 0xe2, 0x3a, 0xfe, 0xda, 0xdb, 0x7f, 0xc7, 0x7f, 0xe0, 0x1f, 0x58, 0xa1, 0x04, 0x72, 0xe8,
	0x96, 0xbd, 0x55, 0xf8, 0x63, 0x5f, 0x93, 0xca, 0xf5, 0xf8, 0x87, 0xa4, 0x2b, 0xf1, 0xf7, 0xe3,
	0xe9, 0x87, 0xd0, 0x7e, 0x6c, 0xfe, 0x58, 0xdf, 0x67, 0x2d, 0xf3, 0xf2, 0xfc, 0xbe, 0x0b, 0x00,
	0x00, 0xff, 0xff, 0xcc, 0x0c, 0xe4, 0xe3, 0x97, 0x04, 0x00, 0x00,
}
