// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protocol/consignment.proto

package consignment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Container struct {
	ContainerId          string   `protobuf:"bytes,1,opt,name=containerId,proto3" json:"containerId,omitempty"`
	CustomerId           string   `protobuf:"bytes,2,opt,name=customerId,proto3" json:"customerId,omitempty"`
	Departure            string   `protobuf:"bytes,3,opt,name=departure,proto3" json:"departure,omitempty"`
	UserId               string   `protobuf:"bytes,4,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1afbce55d4bcd41, []int{0}
}

func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (m *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(m, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func (m *Container) GetContainerId() string {
	if m != nil {
		return m.ContainerId
	}
	return ""
}

func (m *Container) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *Container) GetDeparture() string {
	if m != nil {
		return m.Departure
	}
	return ""
}

func (m *Container) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type Consignment struct {
	ConsignmentId        string       `protobuf:"bytes,1,opt,name=consignmentId,proto3" json:"consignmentId,omitempty"`
	ConsignmentDesc      string       `protobuf:"bytes,2,opt,name=consignmentDesc,proto3" json:"consignmentDesc,omitempty"`
	ConsignmentWeight    int32        `protobuf:"varint,3,opt,name=consignmentWeight,proto3" json:"consignmentWeight,omitempty"`
	Containers           []*Container `protobuf:"bytes,4,rep,name=containers,proto3" json:"containers,omitempty"`
	VesselId             string       `protobuf:"bytes,5,opt,name=vesselId,proto3" json:"vesselId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Consignment) Reset()         { *m = Consignment{} }
func (m *Consignment) String() string { return proto.CompactTextString(m) }
func (*Consignment) ProtoMessage()    {}
func (*Consignment) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1afbce55d4bcd41, []int{1}
}

func (m *Consignment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Consignment.Unmarshal(m, b)
}
func (m *Consignment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Consignment.Marshal(b, m, deterministic)
}
func (m *Consignment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Consignment.Merge(m, src)
}
func (m *Consignment) XXX_Size() int {
	return xxx_messageInfo_Consignment.Size(m)
}
func (m *Consignment) XXX_DiscardUnknown() {
	xxx_messageInfo_Consignment.DiscardUnknown(m)
}

var xxx_messageInfo_Consignment proto.InternalMessageInfo

func (m *Consignment) GetConsignmentId() string {
	if m != nil {
		return m.ConsignmentId
	}
	return ""
}

func (m *Consignment) GetConsignmentDesc() string {
	if m != nil {
		return m.ConsignmentDesc
	}
	return ""
}

func (m *Consignment) GetConsignmentWeight() int32 {
	if m != nil {
		return m.ConsignmentWeight
	}
	return 0
}

func (m *Consignment) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

func (m *Consignment) GetVesselId() string {
	if m != nil {
		return m.VesselId
	}
	return ""
}

type CreateConsignmentReq struct {
	Consignment          *Consignment `protobuf:"bytes,1,opt,name=consignment,proto3" json:"consignment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateConsignmentReq) Reset()         { *m = CreateConsignmentReq{} }
func (m *CreateConsignmentReq) String() string { return proto.CompactTextString(m) }
func (*CreateConsignmentReq) ProtoMessage()    {}
func (*CreateConsignmentReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1afbce55d4bcd41, []int{2}
}

func (m *CreateConsignmentReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateConsignmentReq.Unmarshal(m, b)
}
func (m *CreateConsignmentReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateConsignmentReq.Marshal(b, m, deterministic)
}
func (m *CreateConsignmentReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateConsignmentReq.Merge(m, src)
}
func (m *CreateConsignmentReq) XXX_Size() int {
	return xxx_messageInfo_CreateConsignmentReq.Size(m)
}
func (m *CreateConsignmentReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateConsignmentReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateConsignmentReq proto.InternalMessageInfo

func (m *CreateConsignmentReq) GetConsignment() *Consignment {
	if m != nil {
		return m.Consignment
	}
	return nil
}

type CreateConsignmentRsp struct {
	Created              bool         `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Consignment          *Consignment `protobuf:"bytes,2,opt,name=Consignment,proto3" json:"Consignment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateConsignmentRsp) Reset()         { *m = CreateConsignmentRsp{} }
func (m *CreateConsignmentRsp) String() string { return proto.CompactTextString(m) }
func (*CreateConsignmentRsp) ProtoMessage()    {}
func (*CreateConsignmentRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1afbce55d4bcd41, []int{3}
}

func (m *CreateConsignmentRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateConsignmentRsp.Unmarshal(m, b)
}
func (m *CreateConsignmentRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateConsignmentRsp.Marshal(b, m, deterministic)
}
func (m *CreateConsignmentRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateConsignmentRsp.Merge(m, src)
}
func (m *CreateConsignmentRsp) XXX_Size() int {
	return xxx_messageInfo_CreateConsignmentRsp.Size(m)
}
func (m *CreateConsignmentRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateConsignmentRsp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateConsignmentRsp proto.InternalMessageInfo

func (m *CreateConsignmentRsp) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *CreateConsignmentRsp) GetConsignment() *Consignment {
	if m != nil {
		return m.Consignment
	}
	return nil
}

type GetConsignmentReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConsignmentReq) Reset()         { *m = GetConsignmentReq{} }
func (m *GetConsignmentReq) String() string { return proto.CompactTextString(m) }
func (*GetConsignmentReq) ProtoMessage()    {}
func (*GetConsignmentReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1afbce55d4bcd41, []int{4}
}

func (m *GetConsignmentReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConsignmentReq.Unmarshal(m, b)
}
func (m *GetConsignmentReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConsignmentReq.Marshal(b, m, deterministic)
}
func (m *GetConsignmentReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConsignmentReq.Merge(m, src)
}
func (m *GetConsignmentReq) XXX_Size() int {
	return xxx_messageInfo_GetConsignmentReq.Size(m)
}
func (m *GetConsignmentReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConsignmentReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetConsignmentReq proto.InternalMessageInfo

type GetConsignmentRsp struct {
	Created              bool           `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Consignment          *Consignment   `protobuf:"bytes,2,opt,name=consignment,proto3" json:"consignment,omitempty"`
	Consignments         []*Consignment `protobuf:"bytes,3,rep,name=consignments,proto3" json:"consignments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetConsignmentRsp) Reset()         { *m = GetConsignmentRsp{} }
func (m *GetConsignmentRsp) String() string { return proto.CompactTextString(m) }
func (*GetConsignmentRsp) ProtoMessage()    {}
func (*GetConsignmentRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a1afbce55d4bcd41, []int{5}
}

func (m *GetConsignmentRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConsignmentRsp.Unmarshal(m, b)
}
func (m *GetConsignmentRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConsignmentRsp.Marshal(b, m, deterministic)
}
func (m *GetConsignmentRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConsignmentRsp.Merge(m, src)
}
func (m *GetConsignmentRsp) XXX_Size() int {
	return xxx_messageInfo_GetConsignmentRsp.Size(m)
}
func (m *GetConsignmentRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConsignmentRsp.DiscardUnknown(m)
}

var xxx_messageInfo_GetConsignmentRsp proto.InternalMessageInfo

func (m *GetConsignmentRsp) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *GetConsignmentRsp) GetConsignment() *Consignment {
	if m != nil {
		return m.Consignment
	}
	return nil
}

func (m *GetConsignmentRsp) GetConsignments() []*Consignment {
	if m != nil {
		return m.Consignments
	}
	return nil
}

func init() {
	proto.RegisterType((*Container)(nil), "go.grpc.server.consignment.Container")
	proto.RegisterType((*Consignment)(nil), "go.grpc.server.consignment.Consignment")
	proto.RegisterType((*CreateConsignmentReq)(nil), "go.grpc.server.consignment.CreateConsignmentReq")
	proto.RegisterType((*CreateConsignmentRsp)(nil), "go.grpc.server.consignment.CreateConsignmentRsp")
	proto.RegisterType((*GetConsignmentReq)(nil), "go.grpc.server.consignment.GetConsignmentReq")
	proto.RegisterType((*GetConsignmentRsp)(nil), "go.grpc.server.consignment.GetConsignmentRsp")
}

func init() { proto.RegisterFile("protocol/consignment.proto", fileDescriptor_a1afbce55d4bcd41) }

var fileDescriptor_a1afbce55d4bcd41 = []byte{
	// 402 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x4d, 0x4f, 0xdb, 0x40,
	0x10, 0x95, 0x9b, 0x8f, 0x26, 0xe3, 0x56, 0x51, 0xa6, 0x55, 0xe5, 0xba, 0x55, 0x15, 0x59, 0xad,
	0x9a, 0x43, 0x6b, 0x50, 0x38, 0x72, 0x23, 0x20, 0x14, 0x71, 0x73, 0x0e, 0x48, 0xdc, 0xcc, 0x66,
	0xe4, 0x58, 0x4a, 0xbc, 0xcb, 0xee, 0x26, 0x1c, 0x38, 0xf2, 0xdb, 0xf8, 0x3b, 0xfc, 0x01, 0x2e,
	0x88, 0x25, 0x71, 0xd6, 0x38, 0x24, 0x44, 0xdc, 0xf6, 0xbd, 0xf9, 0x7a, 0xf3, 0x46, 0x5a, 0xf0,
	0x85, 0xe4, 0x9a, 0x33, 0x3e, 0xd9, 0x63, 0x3c, 0x53, 0x69, 0x92, 0x4d, 0x29, 0xd3, 0xa1, 0x21,
	0xd1, 0x4f, 0x78, 0x98, 0x48, 0xc1, 0x42, 0x45, 0x72, 0x4e, 0x32, 0xb4, 0x32, 0x82, 0x5b, 0x07,
	0x9a, 0x7d, 0x9e, 0xe9, 0x38, 0xcd, 0x48, 0x62, 0x07, 0x5c, 0xb6, 0x04, 0x83, 0x91, 0xe7, 0x74,
	0x9c, 0x6e, 0x33, 0xb2, 0x29, 0xfc, 0x05, 0xc0, 0x66, 0x4a, 0xf3, 0xa9, 0x49, 0xf8, 0x60, 0x12,
	0x2c, 0x06, 0x7f, 0x42, 0x73, 0x44, 0x22, 0x96, 0x7a, 0x26, 0xc9, 0xab, 0x98, 0xf0, 0x8a, 0xc0,
	0x6f, 0x50, 0x9f, 0x29, 0x53, 0x59, 0x35, 0xa1, 0x05, 0x0a, 0xee, 0x1d, 0x70, 0xfb, 0x2b, 0x55,
	0xf8, 0x1b, 0x3e, 0x5b, 0x22, 0x73, 0x25, 0x45, 0x12, 0xbb, 0xd0, 0xb2, 0x88, 0x63, 0x52, 0x6c,
	0x21, 0xe8, 0x25, 0x8d, 0xff, 0xa0, 0x6d, 0x51, 0xe7, 0x94, 0x26, 0x63, 0x6d, 0xd4, 0xd5, 0xa2,
	0x72, 0x00, 0x4f, 0x00, 0xf2, 0x95, 0x95, 0x57, 0xed, 0x54, 0xba, 0x6e, 0xef, 0x4f, 0xf8, 0xba,
	0x89, 0x61, 0x6e, 0x60, 0x64, 0x15, 0xa2, 0x0f, 0x8d, 0x39, 0x29, 0x45, 0x93, 0xc1, 0xc8, 0xab,
	0x19, 0x5d, 0x39, 0x0e, 0x62, 0xf8, 0xda, 0x97, 0x14, 0x6b, 0xb2, 0xb6, 0x8e, 0xe8, 0x0a, 0x07,
	0xe6, 0x00, 0x4b, 0xc6, 0xac, 0xed, 0xf6, 0xfe, 0x6e, 0x99, 0x9d, 0x37, 0xb0, 0x6b, 0x83, 0x9b,
	0x75, 0x23, 0x94, 0x40, 0x0f, 0x3e, 0x32, 0xc3, 0x3f, 0xbb, 0xda, 0x88, 0x96, 0xf0, 0x69, 0xb8,
	0x95, 0x6b, 0xbc, 0xdc, 0x65, 0xb8, 0x05, 0x82, 0x2f, 0xd0, 0x3e, 0x25, 0x5d, 0x5c, 0x2e, 0xb8,
	0x73, 0x4a, 0xec, 0x36, 0x3d, 0xec, 0x1d, 0x7a, 0xac, 0x00, 0x9e, 0xc1, 0x27, 0x0b, 0x2a, 0xaf,
	0x62, 0x8e, 0xfa, 0xe6, 0x5e, 0x85, 0xe2, 0xde, 0x83, 0x03, 0xad, 0xe1, 0x38, 0x15, 0x22, 0xcd,
	0x92, 0x21, 0xc9, 0x79, 0xca, 0x08, 0xaf, 0xa1, 0x5d, 0x72, 0x1b, 0xf7, 0x37, 0xf6, 0x5f, 0x73,
	0x7f, 0x7f, 0xc7, 0x0a, 0x25, 0x90, 0x43, 0xab, 0xe8, 0xa9, 0xc2, 0xff, 0x9b, 0x9a, 0x94, 0xce,
	0xe2, 0xef, 0x92, 0xae, 0xc4, 0xd1, 0x8f, 0x8b, 0xef, 0xa1, 0xfd, 0xc9, 0x1c, 0x5a, 0xef, 0xcb,
	0xba, 0xf9, 0x71, 0x0e, 0x1e, 0x03, 0x00, 0x00, 0xff, 0xff, 0x40, 0x2d, 0x5b, 0xda, 0x8f, 0x04,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for ShippingService service

type ShippingServiceClient interface {
	CreateConsignment(ctx context.Context, in *CreateConsignmentReq, opts ...client.CallOption) (*CreateConsignmentRsp, error)
	GetConsignments(ctx context.Context, in *GetConsignmentReq, opts ...client.CallOption) (*GetConsignmentRsp, error)
}

type shippingServiceClient struct {
	c           client.Client
	serviceName string
}

func NewShippingServiceClient(serviceName string, c client.Client) ShippingServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.grpc.server.consignment"
	}
	return &shippingServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *shippingServiceClient) CreateConsignment(ctx context.Context, in *CreateConsignmentReq, opts ...client.CallOption) (*CreateConsignmentRsp, error) {
	req := c.c.NewRequest(c.serviceName, "ShippingService.CreateConsignment", in)
	out := new(CreateConsignmentRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippingServiceClient) GetConsignments(ctx context.Context, in *GetConsignmentReq, opts ...client.CallOption) (*GetConsignmentRsp, error) {
	req := c.c.NewRequest(c.serviceName, "ShippingService.GetConsignments", in)
	out := new(GetConsignmentRsp)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ShippingService service

type ShippingServiceHandler interface {
	CreateConsignment(context.Context, *CreateConsignmentReq, *CreateConsignmentRsp) error
	GetConsignments(context.Context, *GetConsignmentReq, *GetConsignmentRsp) error
}

func RegisterShippingServiceHandler(s server.Server, hdlr ShippingServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&ShippingService{hdlr}, opts...))
}

type ShippingService struct {
	ShippingServiceHandler
}

func (h *ShippingService) CreateConsignment(ctx context.Context, in *CreateConsignmentReq, out *CreateConsignmentRsp) error {
	return h.ShippingServiceHandler.CreateConsignment(ctx, in, out)
}

func (h *ShippingService) GetConsignments(ctx context.Context, in *GetConsignmentReq, out *GetConsignmentRsp) error {
	return h.ShippingServiceHandler.GetConsignments(ctx, in, out)
}
